import struct
import array
import numpy as np

class dictitem:
    def __init__(self, idx, count):
        self.idx = idx
        self.count = np.int64(count)

# Read word2vec from Google's word2vec C code into Python dictionary
class ReadW2V():

    MAXSTRING = 1000

    def __init__(self, filename):
        
        self.fd = open(filename, 'rb')
        self.numvecs = int(self.readstring())
        self.numdims = int(self.readstring())
        self.vectors = {}

    def readstring(self):

        word=''

        for i in xrange(self.MAXSTRING):
            char = self.fd.read(1)
            if char.isspace():
                break
            else:
                word+=char

        return word

    def readfloats(self, num2read):

        arr = array.array('f')
        arr.read(self.fd, num2read)
        return np.array( arr )

    def readfloat(self):

        return struct.unpack('f', self.fd.read(4) )

    def readline(self):
        
        word = self.readstring()
        vec = self.readfloats(self.numdims)
        self.readstring()

        return (word,vec)

    def readlines(self, num2read=0):

        if num2read==0:
            num2read=self.numvecs

        for i in xrange(num2read):
            word, vec =  self.readline()
            self.vectors[word] = vec

        return self.vectors

    def vec2mat(self):

        return np.array(self.vectors.values())

    def words(self):

        return self.vectors.keys()


# Read from a vocab file generated by word2vec
def readvocab(vocabname):
    lines = open(vocabname, 'r').read().splitlines()
    idxdict = []
    worddict = dict()
    for i,line in enumerate(lines):
        word = line.split()[0]
        worddict[word] = dictitem( i, line.split()[1] )
        idxdict.append(word)
    return worddict, idxdict


# Initialize a matrix according to an ordered list: the dictionary
def initVo(wordvecs, listwords):
    '''
    Make a submatrix given a list of words and the reference word vectors
    If a word isn't in the word vectors, then that word vector will be randomly
    initialized. The returned word vector matrix will be in the order of the
    list of words.
    Input: wordvecs, listwords
    '''
    Vo = np.random.randn(len(listwords),len(wordvecs['hello']))
    for i, word in enumerate(listwords):
        if wordvecs.has_key(word):
            Vo[i] = wordvecs[word]
        else:
            print "{} is not in the dictionary".format(word)
    return Vo
